version: "3.8"
services:
    app:
      depends_on:
      - db
      build: ./
      env_file: ./.env
      ports:
        - 3010:5000
      environment: 
        - URI=$URI
        - PORT=$PORT
        - SESSION_SECRET=$SESSION_SECRET
        - HOST=$HOST
        - APP_SECRET=APP_SECRET
        - ACCESS_TOKEN_SECRET=ACCESS_TOKEN_SECRET
    db:
      image: mongo:4.0.28-xenial
      restart: unless-stopped
      env_file: ./.env
      environment:
      - URI=$URI
      ports:
        - 27014:27017
      volumes:
        - db:/data/db
volumes:
  db:
  app: