version: "3.8"
services:
    web:
      build: ./
      ports:
        - 3001:3000
      environment: 
        DB_URL: mongodb://db/faco
    # db:
    #   image: mongo:4.0.28-xenial
    #   ports:
    #     - 27017:27017
volumes:
  webapp: